# Use an existing docker image as a base
FROM node:alpine

# Create a dir for the app
WORKDIR /client

# Copy package.json to /client folder inside docker image
COPY package.json .

# Install dependencies
RUN npm install

# Copy everything to /client folder inside docker image
COPY . .

# Tell the image what to do when it starts as a container
# a.k.a Default command
CMD ["npm", "start"]